id: avmEventResponder
name: AVM Event Responder
description: AVM Event Responder
resource: repository
disabled: false

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: ITA06 - If a new issue is opened add the needs triage label
        if:
          - payloadType: Issues
          - and:
            - isAction:
                action: Opened
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'

      - description: ITA07 - If a new pull request is opened add the needs triage label
        if:
          - payloadType: Pull_Request
          - and:
            - isAction:
                action: Opened
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'

      - description: 'ITA08BCP - If "AVM" or "Azure Verified Modules" is mentioned in a new issue, add label of "Type: AVM :a: :v: :m:" on the issue'
        if:
          - or:
            - payloadType: Issues
            - payloadType: Pull_Request
            - payloadType: Issue_Comment
            - payloadType: Pull_Request_Review_Comment            
          - and:
            - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Created
              - isAction:
                  action: Edited                                    
            - or:
              - bodyContains:
                  pattern: 'AVM'
              - bodyContains:
                  pattern: 'avm'
              - bodyContains:
                  pattern: 'Azure Verified Modules'
              - bodyContains:
                  pattern: 'azure verified modules'                                    
              - commentContains:
                  pattern: 'AVM'
              - commentContains:
                  pattern: 'avm'
              - commentContains:
                  pattern: 'AVM'
              - commentContains:
                  pattern: 'azure verified modules'                  
        then:
          - addLabel:
              label: 'Type: AVM :a: :v: :m:'

      - description: 'ITA09 - When #RR is used in an issue, add the label of "Needs: Author Feedback :ear:"'
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - commentContains:
              pattern: '#RR'
        then:
          - addLabel:
              label: 'Needs: Author Feedback :ear:'

      - description: 'ITA10 - When #wontfix is used in an issue, mark it by using the label of "Status: Won''t Fix :broken_heart:"'
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - commentContains:
              pattern: '#wontfix'
        then:
          - addLabel:
              label: 'Status: Won''t Fix :broken_heart:'
          - closeIssue

      - description: 'ITA11 - When a reply from anyone to an issue occurs, remove the "Needs: Author Feedback :ear:" label and label with "Needs: Attention :wave:"'
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - not:
              isAction:
                action: Closed
          - hasLabel:
              label: 'Needs: Author Feedback :ear:'
        then:
          - removeLabel:
              label: 'Needs: Author Feedback :ear:'
          - addLabel:
              label: 'Needs: Attention :wave:'

      - description: 'ITA12 - Clean email replies on every comment'
        if:
          - payloadType: Issue_Comment
        then:
          - cleanEmailReply

      - description: 'TEST1 - If the type is feature request, assign the "Type: Feature Request :heavy_plus_sign:" label on the issue'
        if:
          - or:
            - payloadType: Issues
            - payloadType: Issue_Comment
          - and:
            - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Created
              - isAction:
                  action: Edited
            - or:
              - bodyContains:
                  pattern: '+ Feature Request'
              - commentContains:
                  pattern: '+ Feature Request'
        then:
          - addLabel:
              label: 'Type: Feature Request :heavy_plus_sign:'
          - removeLabel:
              label: 'Type: Bug :bug:'
          - removeLabel:
              label: 'Type: Security Bug :lock:'

      - description: 'TEST2 - If the type is bug, assign the "Type: Bug :bug:" label on the issue'
        if:
          - or:
            - payloadType: Issues
            - payloadType: Issue_Comment
          - and:
            - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Created
              - isAction:
                  action: Edited
            - or:
              - bodyContains:
                  pattern: '+ Bug'
              - commentContains:
                  pattern: '+ Bug'
        then:
          - addLabel:
              label: 'Type: Bug :bug:'
          - removeLabel:
              label: 'Type: Feature Request :heavy_plus_sign:'
          - removeLabel:
              label: 'Type: Security Bug :lock:'

      - description: 'TEST3 - If the type is security bug, assign the "Type: Security Bug :lock:" label on the issue'
        if:
          - or:
            - payloadType: Issues
            - payloadType: Issue_Comment
          - and:
            - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Created
              - isAction:
                  action: Edited
            - or:
              - bodyContains:
                  pattern: '+ Security Bug'
              - commentContains:
                  pattern: '+ Security Bug'
        then:
          - addLabel:
              label: 'Type: Security Bug :lock:'
          - removeLabel:
              label: 'Type: Bug :bug:'
          - removeLabel:
              label: 'Type: Feature Request :heavy_plus_sign:'

      - description: 'ITA13 - If the language is set to Bicep in the Module proposal, assign the "Language: Bicep :muscle:" label on the issue'
        if:
          - or:
            - payloadType: Issues
            - payloadType: Issue_Comment
          - and:
            - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Created
              - isAction:
                  action: Edited
            - or:
              - bodyContains:
                  pattern: '* Bicep'
              - commentContains:
                  pattern: '* Bicep'
        then:
          - addLabel:
              label: 'Language: Bicep :muscle:'
          - removeLabel:
              label: 'Language: Terraform :globe_with_meridians:'  
      - description: 'ITA14 - If the language is set to Terraform in the Module proposal, assign the "Language: Terraform :globe_with_meridians:" label on the issue'
        if:
          - or:
            - payloadType: Issues
            - payloadType: Issue_Comment
          - and:
            - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Created
              - isAction:
                  action: Edited
            - or:
              - bodyContains:
                  pattern: '* Terraform'
              - commentContains:
                  pattern: '* Terraform'
        then:
          - addLabel:
              label: 'Language: Terraform :globe_with_meridians:'
          - removeLabel:
              label: 'Language: Bicep :muscle:'              
      - description: 'ITA15 - remove the "Needs: Triage" label from a PR, if it already has a "Type: XYZ" label assigned at the time of creating it.'
        if:
          - payloadType: Pull_Request
          - or:
            - hasLabel:
                label: 'Type: Bug :bug:'
            - hasLabel:
                label: 'Type: Documentation :page_facing_up:'
            - hasLabel:
                label: 'Type: Duplicate :palms_up_together:'
            - hasLabel:
                label: 'Type: Feature Request :heavy_plus_sign:'
            - hasLabel:
                label: 'Type: Hygiene :broom:'
            - hasLabel:
                label: 'Type: New Module Proposal :bulb:'
            - hasLabel:
                label: 'Type: Question/Feedback :raising_hand:'
            - hasLabel:
                label: 'Type: Security Bug :lock:'
            - hasLabel:
                label: 'Type: AVM :a: :v: :m:'
          - isAction:
              action: Opened
        then:
          - removeLabel:
              label: 'Needs: Triage :mag:'

      - description: 'ITA16 - Add the "Status: Owners Identified :metal:" label when someone is assigned to a Module Proposal'
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - hasLabel:
              label: 'Type: New Module Proposal :bulb:'
        then:
          - addLabel:
              label: 'Status: Owners Identified :metal:'

      - description: 'ITA17 - If author says they want to be the owner of the module, assign the issue to the author'
        if:
          - payloadType: Issues
          - not:
              isAction:
                action: Opened
          - bodyContains:
              pattern: |
                ### Do you want to be the owner of this module?

                Yes
        then:
          - assignTo:
              author: true
          - addReply:
              reply: |
                @${issueAuthor}, thanks for volunteering to be a module owner! Please don't start the development just yet! 
                The AVM core team will review the proposal and respond to your first. Thank you!