name: Process and Match CSV Data with GitHub API

on:
  push:
    branches:
      - main

jobs:
  process-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download CSV and Process Data
        env:
          CSV_URL: ${{ secrets.CSV_URL }}  # Set your CSV URL in repository secrets
        run: |
          $csvData = Invoke-WebRequest -Uri $env:CSV_URL
          $csv = ConvertFrom-Csv -InputObject $csvData.Content
          $filteredCsv = $csv | Where-Object { $_.D -eq 'Available' }
          $moduleOwners = $filteredCsv | Select-Object -ExpandProperty 'Module Owner'

          foreach ($owner in $moduleOwners) {
            Write-Host "Module Owner: $owner"
          }
        shell: pwsh

      - name: Fetch GitHub Teams and Match with Module Owners
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token
          ORG: 'Azure'  # Replace with your organization name
        run: |
          # Fetch GitHub Teams
          $headers = @{
            Authorization = "token $env:GITHUB_TOKEN"
          }
          $uri = "https://api.github.com/orgs/$env:ORG/teams"
          $teams = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get

          # Match Module Owners with Teams
          foreach ($owner in $moduleOwners) {
              $matchedTeam = $teams | Where-Object { $_.name -eq $owner }
              if ($matchedTeam) {
                Write-Host "Module Owner $owner matched with Team: $($matchedTeam.name)"
              } else {
                Write-Host "No match found for Module Owner: $owner"
              }
          }
        shell: pwsh
