name: AVM - Module Issue ➕🐛🔒
description: Want to request a new Module feature or report a bug? Let us know!
title: "[AVM Module Issue]: "
labels: ["Type: AVM :a: :v: :m:", "Needs: Triage :mag:"]
projects: ["Azure/566"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this AVM Module Issue!

        To help us triage your issue, please provide the below details.

        > **NOTE**: If you'd like to propose a new AVM module, please follow the process described in the [AVM repo](https://aka.ms/AVM/ModuleProposal).
  - type: checkboxes
    id: existing-checks
    attributes:
      label: Check for previous/existing GitHub issues
      description: By submitting this issue, you confirm that you have [searched for previous/existing GitHub issues](https://aka.ms/BRM/TypeAVM) to avoid creating a duplicate.
      options:
        - label: I have checked for previous/existing GitHub issues
          required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type?
      description: How would you best describe this issue? Is this a...
      options:
        - 'Feature Request'
        - 'Bug'
        - 'Security Bug'
        - 'I''m not sure'
    validations:
      required: true
  - type: dropdown
    id: module-name-dropdown
    attributes:
      label: Module Name
      description: Which existing AVM module is this issue related to?
      options:
        - 'Other, as defined below...'
        - 'avm-ptn-avd-lza-insights'
        - 'avm-ptn-avd-lza-managementplane'
        - 'avm-ptn-avd-lza-networking'
        - 'avm-ptn-avd-lza-sessionhosts'
        - 'avm-ptn-securitycenter'
        - 'avm-res-aad-domainservice'
        - 'avm-res-analysisservices-server'
        - 'avm-res-apimanagement-service'
        - 'avm-res-app-containerapp'
        - 'avm-res-app-managedenvironment'
        - 'avm-res-appconfiguration-configurationstore'
        - 'avm-res-authorization-lock'
        - 'avm-res-authorization-policyassignment'
        - 'avm-res-authorization-policydefinition'
        - 'avm-res-authorization-policyexemption'
        - 'avm-res-authorization-policysetdefinition'
        - 'avm-res-authorization-roleassignment'
        - 'avm-res-authorization-roledefinition'
        - 'avm-res-automation-automationaccount'
        - 'avm-res-batch-batchaccount'
        - 'avm-res-cache-redis'
        - 'avm-res-cdn-profile'
        - 'avm-res-cognitiveservices-account'
        - 'avm-res-compute-availabilityset'
        - 'avm-res-compute-diskencryptionset'
        - 'avm-res-compute-disk'
        - 'avm-res-compute-gallery'
        - 'avm-res-compute-image'
        - 'avm-res-compute-proximityplacementgroup'
        - 'avm-res-compute-sshpublickey'
        - 'avm-res-compute-virtualmachine'
        - 'avm-res-compute-virtualmachinescaleset'
        - 'avm-res-consumption-budget'
        - 'avm-res-containerinstance-containergroup'
        - 'avm-res-containerregistry-registry'
        - 'avm-res-containerservice-managedcluster'
        - 'avm-res-databricks-accessconnector'
        - 'avm-res-databricks-workspace'
        - 'avm-res-datafactory-factory'
        - 'avm-res-dataprotection-backupvault'
        - 'avm-res-dbformysql-flexibleserver'
        - 'avm-res-dbforpostgresql-flexibleserver'
        - 'avm-res-desktopvirtualization-applicationgroup'
        - 'avm-res-desktopvirtualization-hostpool'
        - 'avm-res-desktopvirtualization-scalingplan'
        - 'avm-res-desktopvirtualization-workspace'
        - 'avm-res-devtestlab-lab'
        - 'avm-res-digitaltwins-digitaltwinsinstance'
        - 'avm-res-documentdb-databaseaccountname'
        - 'avm-res-eventgrid-domain'
        - 'avm-res-eventgrid-systemtopic'
        - 'avm-res-eventgrid-topic'
        - 'avm-res-eventhub-namespace'
        - 'avm-res-healthbot-healthbot'
        - 'avm-res-healthcareapis-workspace'
        - 'avm-res-insights-actiongroup'
        - 'avm-res-insights-activitylogalert'
        - 'avm-res-insights-component'
        - 'avm-res-insights-datacollectionendpoint'
        - 'avm-res-insights-datacollectionruleassociation'
        - 'avm-res-insights-diagnosticsetting'
        - 'avm-res-insights-metricalert'
        - 'avm-res-insights-privatelinkscopeoperationstatus'
        - 'avm-res-insights-scheduledqueryrule'
        - 'avm-res-insights-webtest'
        - 'avm-res-keyvault-vault'
        - 'avm-res-kubernetesconfiguration-extension'
        - 'avm-res-kubernetesconfiguration-fluxconfiguration'
        - 'avm-res-logic-workflow'
        - 'avm-res-machinelearningservices-workspace'
        - 'avm-res-maintenance-maintenanceconfiguration'
        - 'avm-res-managedidentity-userassignedidentity'
        - 'avm-res-managedservices-registrationdefinition'
        - 'avm-res-management-managementgroup'
        - 'avm-res-netapp-netappaccount'
        - 'avm-res-network-applicationgateway'
        - 'avm-res-network-applicationgatewaywebapplicationfirewallpolicy'
        - 'avm-res-network-applicationsecuritygroup'
        - 'avm-res-network-azurefirewall'
        - 'avm-res-network-bastionhost'
        - 'avm-res-network-connection'
        - 'avm-res-network-ddosprotectionplan'
        - 'avm-res-network-dnsforwardingruleset'
        - 'avm-res-network-dnsresolver'
        - 'avm-res-network-dnszone'
        - 'avm-res-network-expressroutecircuit'
        - 'avm-res-network-expressroutegateway'
        - 'avm-res-network-firewallpolicy'
        - 'avm-res-network-frontdooroperationresult'
        - 'avm-res-network-frontdoorwebapplicationfirewallpolicy'
        - 'avm-res-network-ipgroup'
        - 'avm-res-network-loadbalancer'
        - 'avm-res-network-localnetworkgateway'
        - 'avm-res-network-natgateway'
        - 'avm-res-network-networkinterface'
        - 'avm-res-network-networkmanager'
        - 'avm-res-network-networksecuritygroup'
        - 'avm-res-network-networkwatcher'
        - 'avm-res-network-privatednszone'
        - 'avm-res-network-privateendpoint'
        - 'avm-res-network-privatelinkservice'
        - 'avm-res-network-publicipaddress'
        - 'avm-res-network-publicipprefix'
        - 'avm-res-network-routetable'
        - 'avm-res-network-serviceendpointpolicy'
        - 'avm-res-network-trafficmanagerprofile'
        - 'avm-res-network-virtualhub'
        - 'avm-res-network-virtualnetwork'
        - 'avm-res-network-virtualnetworkgateway'
        - 'avm-res-network-virtualwan'
        - 'avm-res-network-vpngateway'
        - 'avm-res-network-vpnsite'
        - 'avm-res-operationalinsights-workspace'
        - 'avm-res-operationsmanagement-solution'
        - 'avm-res-policyinsights-remediation'
        - 'avm-res-powerbidedicated-capacity'
        - 'avm-res-purview-account'
        - 'avm-res-recoveryservices-vault'
        - 'avm-res-relay-namespace'
        - 'avm-res-resourcegraph-query'
        - 'avm-res-resources-deploymentscript'
        - 'avm-res-resources-resourcegroup'
        - 'avm-res-resources-tags'
        - 'avm-res-search-searchservice'
        - 'avm-res-servicebus-namespace'
        - 'avm-res-servicefabric-cluster'
        - 'avm-res-signalrservice-signalr'
        - 'avm-res-signalrservice-webpubsub'
        - 'avm-res-sql-managedinstance'
        - 'avm-res-sql-server'
        - 'avm-res-storage-storageaccount'
        - 'avm-res-synapse-privatelinkhub'
        - 'avm-res-synapse-workspace'
        - 'avm-res-virtualmachineimages-imagetemplate'
        - 'avm-res-web-connectiongateway'
        - 'avm-res-web-hostingenvironment'
        - 'avm-res-web-serverfarm'
        - 'avm-res-web-site'
        - 'avm-res-web-staticsite'
    validations:
      required: true 
  - type: input
    id: module-name-other
    attributes:
      label: (Optional) Module Name if not listed above
      description: Which existing AVM module is this issue related to (if not listed above)?
      placeholder: avm-res-<rp>-<armresourcename>
    validations:
      required: false
  - type: input
    id: module-version
    attributes:
      label: (Optional) Module Version
      description: Please provide which version(s) of the module does this issue apply to.
    validations:
      required: false
  - type: textarea
    id: question-feedback-text
    attributes:
      label: Description
      description: Please describe the issue!
    validations:
      required: true
  - type: input
    id: correlation-id
    attributes:
      label: (Optional) Correlation Id
      description: Please provide a correlation id f available and appropriate.
    validations:
      required: false
