baseURL = 'https://azure.github.io/AVM-Test/'
languageCode = 'en-us'
title = 'AVM'
theme = 'hugo-theme-relearn'

images = ['images/hero.png']

enableGitInfo = true

[params]
    base = '/AVM-Test'
    disableExplicitIndexURLs = true
    disableLanguageSwitchingButton = false
    themeVariant = [
        { identifier = 'auto', name = 'Zen Light/Dark', auto = [ 'zen-light', 'zen-dark' ] },
        { identifier = 'zen-light'      },
	    { identifier = 'zen-dark'       }
    ]
    disableLandingPageButton = false
    landingPageName = '<i class="fa-fw fas fa-home"></i> Home'
    showVisitedLinks = false
    titleSeparator = '|'
    sidebarmenus = [
      { type = 'menu', identifier = 'defined', main = true, disableTitle = true },
      # { type = 'page', identifier = 'home', main = true, disableTitle = true, pageRef = '' },
      # { type = 'menu', identifier = 'shortcuts', main = false, disableTitle = false },
    ]
    editURL = 'https://github.com/Azure/AVM-Test/edit/main/docs/content/${FilePath}'
    disableInlineCopyToClipBoard = true
    disableAnchorScrolling = false
    alwaysopen = true
    collapsibleMenu = false
    disableRootBreadcrumb = false

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[outputFormats]
  [outputFormats.print]
    baseName = 'print'
    isHTML = true
    mediaType = 'text/html'
    name = 'print'
    noUgly = true
    permalinkable = false

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true

[markup.goldmark.parser]
  autoHeadingID = true
  
# [[menu.defined]]
#   pre = '<i class="fa-fw fas fa-home"></i> '
#   identifier = 'home'
#   name = 'Home'
#   pageRef = '/'
#   weight = 10

[[menu.defined]]
  identifier = 'overview'
  parent = 'home'
  name = 'Overview'
  weight = 1

  [[menu.defined]]
    identifier = 'introduction'
    parent = 'overview'
    name = 'Introduction'
    pageRef = '/overview/introduction'
    weight = 1

[[menu.defined]]
  identifier = 'module-indexes'
  parent = 'home'
  name = 'Module Indexes'
  pageRef = '/indexes'
  weight = 2
  params = { alwaysopen = true }

  [[menu.defined]]
    identifier = 'bicep-module-indexes'
    parent = 'module-indexes'
    name = 'Bicep'
    pageRef = '/indexes/bicep'
    weight = 1
    params = { alwaysopen = false, collapsibleMenu = true }
    
    [[menu.defined]]
      identifier = 'bicep-resource-module-indexes'
      parent = 'bicep-module-indexes'
      name = 'Resource Modules'
      pageRef = '/indexes/bicep/bicep-resource-modules'
      weight = 1
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-pattern-module-indexes'
      parent = 'bicep-module-indexes'
      name = 'Pattern Modules'
      pageRef = '/indexes/bicep/bicep-pattern-modules'
      weight = 2
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-utility-module-indexes'
      parent = 'bicep-module-indexes'
      name = 'Utility Modules'
      pageRef = '/indexes/bicep/bicep-utility-modules'
      weight = 3
      params = { alwaysopen = false, collapsibleMenu = true }

  [[menu.defined]]
    identifier = 'terraform-module-indexes'
    parent = 'module-indexes'
    name = 'Terraform'
    pageRef = '/indexes/terraform'
    weight = 2
    params = { alwaysopen = false, collapsibleMenu = true }
    
    [[menu.defined]]
      identifier = 'terraform-resource-module-indexes'
      parent = 'terraform-module-indexes'
      name = 'Resource Modules'
      pageRef = '/indexes/terraform/tf-resource-modules'
      weight = 1
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'terraform-pattern-module-indexes'
      parent = 'terraform-module-indexes'
      name = 'Pattern Modules'
      pageRef = '/indexes/terraform/tf-pattern-modules'
      weight = 2
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'terraform-utility-module-indexes'
      parent = 'terraform-module-indexes'
      name = 'Utility Modules'
      pageRef = '/indexes/terraform/tf-utility-modules'
      weight = 3
      params = { alwaysopen = false, collapsibleMenu = true }

[[menu.defined]]
  identifier = 'usage'
  parent = 'home'
  name = 'Usage Guide'
  weight = 3

  [[menu.defined]]
    identifier = 'quickstart'
    parent = 'usage'
    name = 'Quickstart'
    pageRef = '/usage/quickstart'
    weight = 1
    params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-quickstart'
      parent = 'quickstart'
      name = 'Bicep'
      pageRef = '/usage/quickstart/bicep'
      weight = 1
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'terraform-quickstart'
      parent = 'quickstart'
      name = 'Terraform'
      pageRef = '/usage/quickstart/terraform'
      weight = 2
      params = { alwaysopen = false, collapsibleMenu = true }

[[menu.defined]]
  identifier = 'specs-defs'
  parent = 'home'
  name = 'Specifications & Definitions'
  weight = 4

  [[menu.defined]]
    identifier = 'module-specs'
    parent = 'specs-defs'
    name = 'Module Specifications'
    pageRef = '/specs-defs/specs'
    weight = 1
    params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-specs'
      parent = 'module-specs'
      name = 'Bicep'
      pageRef = '/specs-defs/specs/bicep'
      weight = 1
      params = { alwaysopen = true, collapsibleMenu = true }

      [[menu.defined]]
        identifier = 'bicep-resource-specs'
        parent = 'bicep-specs'
        name = 'Resource'
        pageRef = '/specs-defs/specs/bicep/resource'
        weight = 1
        params = { alwaysopen = false, collapsibleMenu = true }

        [[menu.defined]]
          identifier = 'bicep-resource-interfaces'
          parent = 'bicep-resource-specs'
          name = 'Interfaces'
          pageRef = '/specs-defs/specs/bicep/resource/interfaces'
          weight = 1
          params = { alwaysopen = true, collapsibleMenu = true }        

      [[menu.defined]]
        identifier = 'bicep-pattern-specs'
        parent = 'bicep-specs'
        name = 'Pattern'
        pageRef = '/specs-defs/specs/bicep/pattern'
        weight = 2
        params = { alwaysopen = true, collapsibleMenu = true }

      [[menu.defined]]
        identifier = 'bicep-utility-specs'
        parent = 'bicep-specs'
        name = 'Utility'
        pageRef = '/specs-defs/specs/bicep/utility'
        weight = 3
        params = { alwaysopen = true, collapsibleMenu = true }          

    [[menu.defined]]
      identifier = 'terraform-specs'
      parent = 'module-specs'
      name = 'Terraform'
      pageRef = '/specs-defs/specs/terraform'
      weight = 2
      params = { alwaysopen = true, collapsibleMenu = true }

      [[menu.defined]]
        identifier = 'terraform-resource-specs'
        parent = 'terraform-specs'
        name = 'Resource'
        pageRef = '/specs-defs/specs/terraform/resource'
        weight = 1
        params = { alwaysopen = false, collapsibleMenu = true }

        [[menu.defined]]
          identifier = 'terraform-resource-interfaces'
          parent = 'terraform-resource-specs'
          name = 'Interfaces'
          pageRef = '/specs-defs/specs/terraform/resource/interfaces'
          weight = 1
          params = { alwaysopen = true, collapsibleMenu = true }        

      [[menu.defined]]
        identifier = 'terraform-pattern-specs'
        parent = 'terraform-specs'
        name = 'Pattern'
        pageRef = '/specs-defs/specs/terraform/pattern'
        weight = 2
        params = { alwaysopen = true, collapsibleMenu = true }

      [[menu.defined]]
        identifier = 'terraform-utility-specs'
        parent = 'terraform-specs'
        name = 'Utility'
        pageRef = '/specs-defs/specs/terraform/utility'
        weight = 3
        params = { alwaysopen = true, collapsibleMenu = true }          

    [[menu.defined]]
      identifier = 'terraform-specs'
      parent = 'module-specs'
      name = 'Terraform'
      pageRef = '/specs-defs/specs/terraform'
      weight = 2
      params = { alwaysopen = true, collapsibleMenu = true }         


[[menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = 'GitHub Repo'
  url = 'https://github.com/McShelby/hugo-theme-relearn'
  weight = 10

[[menu.shortcuts]]
  name = 'Showcases'
  pageRef = '/showcase'
  weight = 20

[[menu.shortcuts]]
  name = 'Credits'
  pageRef = '/more/credits'
  weight = 30

[[menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-tags"></i> '
  name = 'Tags'
  pageRef = '/tags'
  weight = 40

[[menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-layer-group"></i> '
  name = 'Categories'
  pageRef = '/categories'
  weight = 50