baseURL = 'https://azure.github.io/AVM-Test/'
languageCode = 'en-us'
title = 'AVM'
theme = 'hugo-theme-relearn'

images = ['images/hero.png']

[params]
    base = '/AVM-Test'
    disableExplicitIndexURLs = true
    disableLanguageSwitchingButton = false
    themeVariant = [
        { identifier = 'auto', name = 'Zen Light/Dark', auto = [ 'zen-light', 'zen-dark' ] },
        { identifier = 'zen-light'      },
	    { identifier = 'zen-dark'       }
    ]
    disableLandingPageButton = false
    landingPageName = '<i class="fa-fw fas fa-home"></i> Azure Verified Modules'
    showVisitedLinks = false
    titleSeparator = '|'
    sidebarmenus = [
      { type = 'page', identifier = 'home', main = true, disableTitle = true, pageRef = '' },
      { type = 'menu', identifier = 'defined', main = true, disableTitle = true },
      # { type = 'menu', identifier = 'shortcuts', main = false, disableTitle = false },
    ]
    editURL = 'https://github.com/Azure/AVM-Test/edit/main/docs/content/${FilePath}'
    disableAnchorScrolling = false

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[outputFormats]
  [outputFormats.print]
    baseName = 'print'
    isHTML = true
    mediaType = 'text/html'
    name = 'print'
    noUgly = true
    permalinkable = false

[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true
  
# [[menu.defined]]
#   pre = '<i class="fa-fw fas fa-home"></i> '
#   identifier = 'home'
#   name = 'Home'
#   pageRef = '/'
#   weight = 10

# [[menu.defined]]
#   identifier = 'overview'
#   parent = 'home'
#   name = 'Overview'
#   weight = 20

#   [[menu.defined]]
#     identifier = 'introduction'
#     parent = 'overview'
#     name = 'Introduction'
#     pageRef = '/overview/introduction'
#     weight = 30



[[menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = 'GitHub Repo'
  url = 'https://github.com/McShelby/hugo-theme-relearn'
  weight = 10

[[menu.shortcuts]]
  name = 'Showcases'
  pageRef = '/showcase'
  weight = 20

[[menu.shortcuts]]
  name = 'Credits'
  pageRef = '/more/credits'
  weight = 30

[[menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-tags"></i> '
  name = 'Tags'
  pageRef = '/tags'
  weight = 40

[[menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-layer-group"></i> '
  name = 'Categories'
  pageRef = '/categories'
  weight = 50