baseURL = 'azure.github.io/AVM-Test'
languageCode = 'en-us'
title = 'AVM'
theme = 'hugo-theme-relearn'

images = ['images/hero.png']

[params]
    disableExplicitIndexURLs = true
    disableLanguageSwitchingButton = false
    themeVariant = [
        { identifier = 'auto', name = 'Zen Light/Dark', auto = [ 'zen-light', 'zen-dark' ] },
        { identifier = 'zen-light'      },
	    { identifier = 'zen-dark'       }
    ]
    disableLandingPageButton = true
    landingPageName = '<i class="fa-fw fas fa-home"></i> Azure Verified Modules'
    showVisitedLinks = false
    titleSeparator = '|'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[outputFormats]
  [outputFormats.print]
    baseName = 'print'
    isHTML = true
    mediaType = 'text/html'
    name = 'print'
    noUgly = true
    permalinkable = false

[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true
  
[menus]
  [[menus.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 20
  [[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 30