# Add new issues to the correct project
name: '.Platform: Assign Issue to Project'

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add Issues to Projects
    runs-on: ubuntu-latest
    steps:
      - name: 'Add Bug to Bug Board'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: pwsh
        run: |
          $title = 'Test issue'
          $body = 'test body'
          $repo = 'Azure/GHPolicyTest'
          $issueUrl = gh issue create --title $title --body $body --repo $Repo
          $issueId = (gh issue view $issueUrl --repo $repo --json 'id'  | ConvertFrom-Json -Depth 100).id
          Write-Host '#####'
          Write-Host $issueUrl
          Write-Host $issueId

          $project = gh api graphql -f query='
            query($organization: String! $number: Int!){
              organization(login: $organization){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f organization="Azure" -F number=614 | ConvertFrom-Json -Depth 10

          $bugBoardId = $project.data.organization.projectV2.id

          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$bugBoardId -f issue=$issueId --jq '.data.addProjectV2ItemById.projectV2Item.id'
