# Workflow for syncing CSV labels to GitHub Labels
name: Github Team - Check Existance

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: "0 10 * * 1-5" # At 10:00 AM, Monday through Friday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

permissions: read-all

jobs:
  Check-Team-Existance:
    name: Check-Team-Existance
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # [Setup] task(s)
      # ---------------
      - name: "Setup agent"
        shell: pwsh
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Set-EnvironmentOnAgent.ps1')

          # Define PS modules to install on the runner
          $modules = @(
              @{ Name = 'Az.Accounts' },
              @{ Name = 'Az.Resources' }
          )

          # Set agent up
          Set-EnvironmentOnAgent -PSModules $modules

      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TEAM_LINTER_APP_ID }}
          private_key: ${{ secrets.TEAM_LINTER_PRIVATE_KEY }}

      - name: "Compare Bicep Owners Resource Teams"
        if: always()
        id: comparebcpowner
        shell: pwsh
        run: |
          # Group Task Logs
          Write-Output '::group::Compare AVM Bicep Team Configuration'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Compare-AvmTeams.ps1')

          $functionInput = @{
            ModuleIndex           = 'Bicep-Resource'
            TeamFilter            = 'BicepResourceOwners'
            ValidateOwnersParent  = $true

          }

          Write-Verbose 'Invoke task with' -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Compare-AvmTeams @functionInput -Verbose 

          # End Group Task Logs
          Write-Output '::endgroup::'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      
      - name: "Compare Bicep Contributor Resource Teams"
        if: always()
        id: comparebcpcontrib
        shell: pwsh
        run: |
          # Group Task Logs
          Write-Output '::group::Compare AVM Bicep Team Configuration'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Compare-AvmTeams.ps1')

          $functionInput = @{
            ModuleIndex           = 'Bicep-Resource'
            TeamFilter            = 'BicepResourceContributors'
            ValidateOwnersParent  = $true
            CreateIssues          = $true
          }

          Write-Verbose 'Invoke task with' -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Compare-AvmTeams @functionInput -Verbose 

          # End Group Task Logs
          Write-Output '::endgroup::'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: "Compare Terraform Resource Teams"
        if: always()
        id: comparetf
        shell: pwsh
        run: |
          # Group Task Logs
          Write-Output '::group::Compare AVM Terraform Team Configuration'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Compare-AvmTeams.ps1')

          $functionInput = @{
            ModuleIndex           = 'Terraform-Resource'
            TeamFilter            = 'AllTerraformResource'
            ValidateOwnersParent  = $true
          }

          Write-Verbose 'Invoke task with' -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Compare-AvmTeams @functionInput -Verbose 

          # End Group Task Logs
          Write-Output '::endgroup::'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
