# Workflow for testing all module index CSVs
name: .Platform - Test Module Index CSVs

on:
  pull_request:
    paths:
      - 'docs/static/module-indexes/**'
  workflow_dispatch: {}

defaults:
  run:
    shell: pwsh

jobs:
  Test-Module-Index-CSVs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test BicepResourceModules.csv
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "BicepResourceModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.checkout.outcome == 'success' }}


      - name: Test BicepPatternModules.csv
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "BicepPatternModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.checkout.outcome == 'success' }}

      - name: Test BicepUtilityModules.csv
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "BicepUtilityModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.checkout.outcome == 'success' }}

      - name: Test TerraformResourceModules.csv
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "TerraformResourceModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.checkout.outcome == 'success' }}


      - name: Test TerraformPatternModules.csv
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "TerraformPatternModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.checkout.outcome == 'success' }}

      - name: Test TerraformUtilityModules.csv
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "TerraformUtilityModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.checkout.outcome == 'success' }}