# Workflow for testing all module index CSVs
name: .Platform - Test Module Index CSVs

on:
  pull_request:
    paths:
      - 'docs/static/module-indexes/**'
  workflow_dispatch: {}

defaults:
  run:
    shell: pwsh

jobs:
  Test-Module-Index-CSVs:
    runs-on: ubuntu-latest
    
    continue-on-error: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Bicep Resource Module Index CSV
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "BicepResourceModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Bicep Pattern Module Index CSV
        shell: pwsh
        run: |
          $RepoRoot = $env:GITHUB_WORKSPACE

          . (Join-Path $RepoRoot "utilities" "tools" "module-indexes" "Test-AvmModuleIndexCsv.ps1") -CsvFiles $(Join-Path $RepoRoot "docs" "static" "module-indexes" "BicepPatternModules.csv")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          